# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  -
    # Additional files/template/globs you want to add to the archive.
    files:
      - LICENSE

    # Can be used to change the archive formats for specific GOOSs.
    format_overrides:
      - goos: windows
        format: zip
